import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AuthNav from "@/components/AuthNav";
import NextAuthSessionProvider from "@/components/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider>
          <header className="bg-white border-b shadow-sm sticky top-0 z-50">
            <nav className="container mx-auto flex items-center justify-between py-4 px-4 md:px-0">
              <div className="flex items-center gap-6">
                <Link href="/" className="text-xl font-bold text-gray-900 hover:text-blue-600 transition-colors">
                  Dashboard
                </Link>
                <Link href="/orders" className="text-gray-700 hover:text-blue-600 transition-colors">
                  Pizza Orders
                </Link>
              </div>
              <AuthNav />
            </nav>
          </header>
          <main className="container mx-auto px-4 md:px-0 py-8">
            {children}
          </main>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
